### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by ryanmcgrath** [onjin/docker-alpine-postgres#2]
Love the image! Small issue when trying to use it - seems there's a permissions issue in the latest one?

``` bash
postgres_1  | FATAL:  data directory "/var/lib/postgresql/data" has group or world access
postgres_1  | DETAIL:  Permissions should be u=rwx (0700).
```

I believe you're missing this in your entrypoint somewhere. I don't have the time to debug it myself but figured I'd leave a note - would be cool to see it patched up!

``` bash
chmod 700 "$PGDATA"
```

**Comment by onjin** [comment]
Thank you very much for this feedback. I'll follow this issue and fix it

**Comment by onjin** [comment]
Hi,

i added `chmod 0700` before initdb, but if you change volume dir permission outside of docker,
before next start the problem will still persist.

You need to run `sudo chmod 0770 volumedir` also outside of docker to fix it.
