### ISSUE TITLE
Tag patch level versions.

### ISSUE THREAD

**Issue by mrmachine** [onjin/docker-alpine-postgres#7]
Related to #6 -- when the `9.4` tag was updated and started failing, our first thought was to update our compose file to use `9.4.9`. But despite what the README on Docker Hub says, which shows tags for patch level (`9.4.N`) and minor level (`9.4`) versions, Docker Hub tags page shows *only* minor level versions, and we were unable to `docker pull` any previous patch level versions.

With minor level version tags which are updated semi-frequently, we are at the mercy of our builds or deployments breaking not only from changes to PostgreSQL itself (which we *might* assume are backwards compatible) but also any other changes to the build, as seen in #6.

Please could you change your build process to ensure that patch level builds are always tags, and that those tags are permanent -- if we tag `9.4.9`, we expect to *always* get the same build.

I was about to say that it looks like this is what the official postgres image does, and when I checked their tags page on Docker Hub I noticed that they also have alpine builds, now.

Does that make your repository redundant now? Are you going to still maintain your repository when the official repository also has alpine builds?

**Comment by onjin** [comment]
Hi,

I've added notice to readme that official postgresql already introduces alpine builds so there is no general reasons to use this repository.

But also I've changed build process to make tags permanent.
